Fix comparison of Float with String failed when WD_CACHE_TIME is set
ArgumentError: comparison of Float with String failed
/home/runner/dossier/vendor/bundle/ruby/2.4.0/gems/webdrivers-4.0.0.rc1/lib/webdrivers/system.rb:48:in `<'
/home/runner/dossier/vendor/bundle/ruby/2.4.0/gems/webdrivers-4.0.0.rc1/lib/webdrivers/system.rb:48:in `valid_cache?'
/home/runner/dossier/vendor/bundle/ruby/2.4.0/gems/webdrivers-4.0.0.rc1/lib/webdrivers/common.rb:153:in `with_cache'
/home/runner/dossier/vendor/bundle/ruby/2.4.0/gems/webdrivers-4.0.0.rc1/lib/webdrivers/chromedriver.rb:34:in `latest_version'
/home/runner/dossier/vendor/bundle/ruby/2.4.0/gems/webdrivers-4.0.0.rc1/lib/webdrivers/common.rb:127:in `correct_binary?'
/home/runner/dossier/vendor/bundle/ruby/2.4.0/gems/webdrivers-4.0.0.rc1/lib/webdrivers/common.rb:83:in `update'
/home/runner/dossier/vendor/bundle/ruby/2.4.0/gems/webdrivers-4.0.0.rc1/lib/webdrivers/tasks/chromedriver.rake:25